sudo: false
language: php
matrix:
  fast_finish: true
  include:
  - php: '5.2'
  - php: '5.6'
    env: SNIFF=1
  - php: '7.0'
  - php: hhvm
  allow_failures:
  - php: hhvm
before_script:
- export PHPCS_DIR=/tmp/phpcs
- export SNIFFS_DIR=/tmp/sniffs
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git
  $PHPCS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  $SNIFFS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git
  $SNIFFS_DIR/PHPCompatibility; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs --config-set installed_paths
  $SNIFFS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi
- if [[ "$SNIFF" == "1" ]]; then npm install -g jscs; fi
- if [[ "$SNIFF" == "1" ]]; then npm install -g jshint; fi
- if [[ "$SNIFF" == "1" ]]; then wget https://develop.svn.wordpress.org/trunk/.jshintrc;
  fi
script:
- find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- if [[ "$SNIFF" == "1" ]]; then jshint .; fi
- if [[ "$SNIFF" == "1" ]]; then jscs .; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml
  --extensions=php; fi
notifications:
  email: false
  slack:
    secure: XguKu5kdrJyPqq4suwHGVbIwcUVwKs25/qphSY7I29RbSgPP+PrUginK44SNMl/nRB+NAnZuA650UQfNflz1p4kIp55wxnEsAARjSvHWfl5WLb6oPG8lk89eE1mRUJ+R8+I5fQq1euO6a6dY5i+asWVv2Ghc9mPaowCl9+9IBewXSBsUZhrghv+W7LH61IEPorobnFSEdXFDjFH17g/dK3znbL2lI21BeTnotwSB9D6FN3l0Zv+NMesbDlamVUUdHwfTzKeGGk9HjV07i+lYfBFLU8Jpl2FnzYuqLYRO/t2nR8/4HJy3StGCdeeqB7rmPpBPnMwbaj4fpXreui6Nj4h/dZ9hW2+L2hrpturCTVEnhQIQ3CmYvAdjWvVfhkL2JdaU5ScNC1KsBQo8XrO9KkRkArs5YDe/zNzLhrAxmkf+9eHKfNF48Eq26UDj1tinto4oHshACIiJvaChveWz+LdyRsIn7iMyrmdX+UCRg84P3n0oiIVVH4MZu5lCpQzmN3Ej8vYLMlTlHMO/VqAgwlWqAPLoYqSeaZozGbT8Xny7mgrh0ix29yNpvvmX/sXUUOE17aS7QWMwX9JBgI/xOlOzVPqdk+7BZDlUqx4ByDGePd2F3NbNfHR6WIZY8nUGCkKEw+vSLeRBfQs1BRZ8Z1MqPNgXNHSWeYbUZAwsLbY=
